[pytest]
testpaths = test
python_files = *test*.py
python_classes = *Test*
python_functions = *test*
addopts = --alluredir=allure-files
markers =
    ui: UI-тесты (Selenium)
    api: API-тесты (requests)
